# Generated by Django 4.1.1 on 2022-09-06 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ciudadano',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(db_column='nombresCompletos', max_length=250, verbose_name='Nombres Completos')),
                ('apellido', models.CharField(db_column='apellidos', max_length=100, verbose_name='Apellidos')),
                ('t_doc', models.CharField(choices=[('CC', 'Cédula de Ciudadanía'), ('TI', 'Tarjeta de Identidad'), ('CE', 'Cédula de Extranjería')], db_column='tDocumento', default='CC', max_length=2)),
                ('no_documento', models.CharField(db_column='nDocumento', max_length=10, verbose_name='Número de documento')),
                ('sexo', models.CharField(choices=[('M', 'Hombre'), ('F', 'Mujer'), ('IS', 'Intersexual'), ('I', 'Indefinido'), ('PD', 'Prefieren no decir')], db_column='sexo', default='M', max_length=2)),
                ('telefono_c', models.CharField(db_column='tCelular', max_length=10, null=True, verbose_name='Teléfono Celular')),
                ('telefono_f', models.CharField(db_column='tFijo', max_length=10, null=True, verbose_name='Teléfono Fijo')),
                ('correo', models.EmailField(db_column='correo', max_length=254, verbose_name='Correo Electrónico')),
                ('departamento', models.CharField(db_column='departamento', max_length=80, verbose_name='Departamento')),
                ('municipio', models.CharField(db_column='municipio', max_length=80, verbose_name='Municipio')),
                ('direccion', models.CharField(db_column='dirección', max_length=150, null=True, verbose_name='Dirección')),
                ('barrio', models.CharField(db_column='barrio', max_length=80, verbose_name='Barrio/Vereda')),
                ('f_nacimiento', models.DateField(db_column='fNacimiento', verbose_name='Fecha de Nacimiento')),
                ('etnia', models.CharField(db_column='etnia', max_length=50)),
                ('discapacidad', models.CharField(choices=[('A', 'Auditiva'), ('V', 'Visual'), ('C', 'Cognitiva'), ('F', 'Física'), ('O', 'Otra'), ('NA', 'No aplica')], db_column='discapacidad', default='NA', max_length=2)),
                ('estrato', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], db_column='estrato', max_length=2)),
                ('n_educativo', models.CharField(choices=[('PA', 'Primaria'), ('B', 'Bachiller'), ('T', 'Técnico'), ('TG', 'Tecnolólogo'), ('P', 'Profesional')], db_column='nEducativo', max_length=2)),
                ('d_tecnologicos', models.CharField(choices=[('SI', 'Sí'), ('NO', 'No')], db_column='dTecnologicos', max_length=2)),
                ('dispositivos', models.CharField(choices=[('TM', 'T. Móvil'), ('C', 'Computador'), ('T', 'Tablet'), ('OC', 'Otro ¿Cuál?')], db_column='dispositivos', max_length=2)),
                ('conectividad', models.CharField(choices=[('SI', 'Sí'), ('NO', 'No')], db_column='conectividad', max_length=2)),
                ('t_afiliacion', models.CharField(choices=[('S', 'Subsidiado'), ('C', 'Contributivo')], db_column='afiliacion', max_length=2)),
                ('estado', models.BooleanField(default=True)),
            ],
        ),
    ]
