# Generated by Django 4.1.1 on 2022-09-07 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Sondeo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sondeo',
            name='icono',
            field=models.ImageField(default='media/icon.png', upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='sondeo',
            name='idTema',
            field=models.ForeignKey(db_column='idTema', on_delete=django.db.models.deletion.CASCADE, to='Sondeo.tema', verbose_name='Tema'),
        ),
    ]
