# Generated by Django 4.1.1 on 2022-09-06 21:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Sondeo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pregunta', models.TextField(db_column='pregunta')),
                ('idSondeo', models.ForeignKey(db_column='idSondeo', on_delete=django.db.models.deletion.CASCADE, to='Sondeo.sondeo')),
            ],
        ),
        migrations.CreateModel(
            name='Tema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tema', models.TextField(db_column='tema')),
            ],
        ),
        migrations.DeleteModel(
            name='Preguntas',
        ),
        migrations.AddField(
            model_name='pregunta',
            name='idTema',
            field=models.ForeignKey(db_column='idTema', on_delete=django.db.models.deletion.CASCADE, to='Sondeo.tema'),
        ),
    ]
