# Generated by Django 4.1.1 on 2022-09-08 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sondeo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sondeo',
            name='conectividad',
            field=models.CharField(blank=True, choices=[('SI', 'Sí'), ('NO', 'No')], db_column='conectividad', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='sondeo',
            name='d_tecnologicos',
            field=models.CharField(blank=True, choices=[('SI', 'Sí'), ('NO', 'No')], db_column='dTecnologicos', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='sondeo',
            name='discapacidad',
            field=models.CharField(blank=True, choices=[('A', 'Auditiva'), ('V', 'Visual'), ('C', 'Cognitiva'), ('F', 'Física'), ('O', 'Otra'), ('NA', 'No aplica')], db_column='discapacidad', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='sondeo',
            name='dispositivos',
            field=models.CharField(blank=True, choices=[('TM', 'T. Móvil'), ('C', 'Computador'), ('T', 'Tablet'), ('OC', 'Otro ¿Cuál?')], db_column='dispositivos', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='sondeo',
            name='estrato',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], db_column='estrato', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='sondeo',
            name='n_educativo',
            field=models.CharField(blank=True, choices=[('PA', 'Primaria'), ('B', 'Bachiller'), ('T', 'Técnico'), ('TG', 'Tecnolólogo'), ('P', 'Profesional')], db_column='nEducativo', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='sondeo',
            name='sexo',
            field=models.CharField(blank=True, choices=[('M', 'Hombre'), ('F', 'Mujer'), ('IS', 'Intersexual'), ('I', 'Indefinido'), ('PD', 'Prefieren no decir')], db_column='sexo', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='sondeo',
            name='t_afiliacion',
            field=models.CharField(blank=True, choices=[('S', 'Subsidiado'), ('C', 'Contributivo')], db_column='afiliacion', max_length=2, null=True),
        ),
    ]
