# Generated by Django 4.1.1 on 2022-09-08 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sondeo', '0002_alter_sondeo_conectividad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sondeo',
            name='estado',
            field=models.CharField(choices=[('abierto', 'Abierto'), ('publicado', 'Publicado'), ('eliminado', 'Eliminado')], db_column='estado', default='abierto', max_length=9),
        ),
    ]
