# Generated by Django 4.1.1 on 2022-09-06 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sondeo', '0002_pregunta_tema_delete_preguntas_pregunta_idtema'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tema',
            name='tema',
            field=models.CharField(db_column='tema', max_length=250),
        ),
    ]
