# Generated by Django 4.1.1 on 2022-09-07 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sondeo', '0002_alter_sondeo_icono_alter_sondeo_idtema'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pregunta',
            name='idParametro',
        ),
    ]
